//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDetails()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id_details { get; set; }
        public int id_mark { get; set; }
        public Nullable<int> detail_articul { get; set; }
        public string year_release { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string kuzov_type { get; set; }
    
        public virtual CarMark CarMark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
