//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarMark()
        {
            this.CarDetails = new HashSet<CarDetails>();
        }
    
        public int id_mark { get; set; }
        public string mark_name { get; set; }
        public string country_of_origin { get; set; }
        public string KPP_type { get; set; }
        public Nullable<bool> supply_contract { get; set; }
        public byte[] photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarDetails> CarDetails { get; set; }
    }
}
